### ISSUE TITLE
OSX Yosemite python

### ISSUE THREAD

**Issue by losandros** [synack/knockknock#18]
Hi
I made some tests with OSX Yosemite and initially had problems running the knockknock.py. I also had the "argparse" error. Under Yosemite this can be easily resolved by just running the script with the correct python binary that comes with Yosemite:
"python2.7 knockknock.py" instead of "python knockknock.py"

That solved my issues and it's running fine on Yosemite. I finally found some legacy stuff from the Blackberry Desktop software and some other extensions. 

Thanks!

**Comment by dguido** [comment]
This works for me with the default Yosemite python.

**Comment by patrickwardle** [comment]
Yes, KnockKnock should be run with the OS's version of python (/usr/bin/python)
