### ISSUE TITLE
Missing Various Startup Processes

### ISSUE THREAD

**Issue by secretsquirrel** [synack/knockknock#22]
I've found that knockknock misses various startup binaries if they are modified and I am compiling a full list for both Yosemite and Mavericks.  Would you want them posted here or out of band (email)?

**Comment by patrickwardle** [comment]
thanks for your research into this! Email (patrick@synack.com) would probably be easiest - esp if I have follow up questions/discussions etc.

**Comment by secretsquirrel** [comment]
Thanks for working with me on this!

Closing this out as I believe OSXCollector from Yelp solved the issue by collecting all artifacts on disk. Albeit taking a LONG time.

https://github.com/Yelp/osxcollector
