### ISSUE TITLE
Adblock whitelisting

### ISSUE THREAD

**Issue by orangewise** [synack/knockknock#26]
Hi,

I'm trying to whitelist Adblock, no luck so far. Below is the output. Any suggestions?

Thanks!

[Safari Browser Extensions]

AdBlock-2.safariextension 
 description: None
 id: None
 path: /Users/ronald/Library/Safari/Extensions/Extensions.plist/AdBlock-2.safariextz

**Comment by patrickwardle** [comment]
you could manually edit the whitelistedExtensions.json file?

**Comment by orangewise** [comment]
That does not work since there is no id...

**Comment by orangewise** [comment]
Hi Patrick, I have created a small PR:
https://github.com/synack/knockknock/pull/29

Please let me know what you think...

**Comment by orangewise** [comment]
Thanks for merging :)
