### ISSUE TITLE
VT integration

### ISSUE THREAD

**Issue by dguido** [synack/knockknock#5]
Configure with API key, search VT for hashes and give thumbs up/thumbs down on every file (percentage?).

**Comment by karlhiramoto** [comment]
Yes, and upload  unknown samples to VT :-)

**Comment by sroberts** [comment]
@karlhiramoto That needs to be an explicit decision with the user permission. Otherwise you risk leaking a lot.

**Comment by patrickwardle** [comment]
latest version now queries VirusTotal (via file hash) to get the detection ratio for all items. Still need to add option to upload unknown files (with user's permission of course)

**Comment by sroberts** [comment]
@patrickwardle: :heart:
